pb_role_modifiers = {
    "COM": "Comitative",
    "LOC": "Locative",
    "DIR": "Directional",
    "GOL": "Goal",
    "MNR": "Manner",
    "TMP": "Temporal",
    "EXT": "Extent",
    "REC": "Reciprocals",
    "PRD": "Secondary_Predication",
    "PRP": "Purpose",
    "CAU": "Cause",
    "DIS": "Discourse",
    "ADV": "Adverbials",
    "ADJ": "Adjectival",
    "MOD": "Modal",
    "NEG": "Negation",
    "DSP": "Direct_Speech",
    "LVB": "Light_Verb",
    "CXN": "Construction",
    "PAG": "Agent",
    "PPT": "Patient",
    "VSP": "Verb-specific"
}

